classdef RetinoStimObj
    properties
        centerVals
        Radius
        degreeRadius
        stimStrobeNum
        reps
        stimTime
        holdTime
        waitTime
        numStimuli
        w_pixels
        h_pixels
        spatFreq
        mmPerPixel
        DistToScreen
        orient
        phase
    end
end