classdef RetinoCallStimObj
    properties
        driftSpeed
        driftTime
        stimFreq
        Width
        w_pixels
        h_pixels
        reps
        checkRefresh
        holdTime
        centerPos
        Flashes
        numDirs
        DistToScreen
        DirNames
        mmPerPixel
        ifi
        theta
        phi
    end
end
